"""Evaluate trained models and record the results as build artifacts.

Run it as a module::

    python -m src.evaluate                      # every available model, test split
    python -m src.evaluate --models lr lstm
    python -m src.evaluate --split validation
    python -m src.evaluate --include-base       # also the untouched base checkpoint
    python -m src.evaluate --include-base --base-model <checkpoint>  # another base
    python -m src.evaluate --table-only         # re-print the table, evaluate nothing

Each run writes reports/metrics/<model>.json and prints a Markdown table meant to
be pasted straight into the README. That indirection is the point: the project's
documentation once claimed 92-95% accuracy for a model whose own checkpoint
recorded 78.9%, because the numbers were typed by hand and the training scripts
printed their metrics and discarded them. A number that cannot be regenerated by
a command is not evidence.
"""

from __future__ import annotations

import argparse
import logging
import sys
from datetime import UTC, datetime

import numpy as np

from src.config import (
    BASELINE_DISPLAY_NAME,
    BASELINE_KEY,
    BASELINE_PREPROCESSING,
    DATASET_CONFIG,
    DATASET_NAME,
    LABELS,
    METRICS_DIR,
    MODEL_ALIASES,
    MODEL_KEYS,
    ROBERTA_CONFIG,
    resolve_model,
)
from src.data import class_distribution, load_raw_dataset
from src.inference.predictor import (
    ModelUnavailableError,
    RobertaPredictor,
    available_models,
    check_artifacts,
    load_predictor,
)
from src.utils.io import load_json, save_json
from src.utils.metrics import build_report, compute_metrics

LOGGER = logging.getLogger(__name__)

DEFAULT_SPLIT = "test"
DEFAULT_BATCH_SIZE = 64


def baseline_key(base_model: str | None = None) -> str:
    """Record key for a base checkpoint scored zero-shot.

    The configured base keeps the plain key; any other checkpoint gets a
    suffix from its name, so its record sits beside the default's rather
    than overwriting it.
    """
    if base_model is None or base_model == ROBERTA_CONFIG.base_model:
        return BASELINE_KEY
    slug = "".join(c if c.isalnum() else "_" for c in base_model.split("/")[-1])
    return f"{BASELINE_KEY}__{slug}"


def baseline_display_name(base_model: str | None = None) -> str:
    if base_model is None or base_model == ROBERTA_CONFIG.base_model:
        return BASELINE_DISPLAY_NAME
    return f"{base_model} (base, not fine-tuned)"


def baseline_hyperparameters(base_model: str | None = None) -> dict:
    """What a baseline record says about itself, in place of training settings."""
    return {
        "base_model": base_model or ROBERTA_CONFIG.base_model,
        "preprocessing": BASELINE_PREPROCESSING,
        "fine_tuned": False,
    }


def is_baseline(model: str) -> bool:
    return model == BASELINE_KEY or model.startswith(f"{BASELINE_KEY}__")


class BaselinePredictor(RobertaPredictor):
    """A base checkpoint straight from the Hub, for evaluation only.

    Deliberately bypasses ``Predictor.__init__``: there are no local artifacts
    to check, no calibration file and no version to digest. It is not
    registered with ``load_predictor`` and its key is not in ``MODEL_KEYS``,
    so nothing that serves predictions can reach it.
    """

    def __init__(
        self,
        base_model: str | None = None,
        batch_size: int = 16,
        device: str | None = None,
    ) -> None:
        import torch
        from transformers import AutoModelForSequenceClassification, AutoTokenizer

        base = base_model or ROBERTA_CONFIG.base_model
        self.key = baseline_key(base)
        self.display_name = baseline_display_name(base)
        self.temperature = 1.0
        # The preprocessing the checkpoint was trained with, not ours.
        self.preprocessing = BASELINE_PREPROCESSING
        self.version = base

        self._torch = torch
        self._batch_size = batch_size
        self.device = device or ("cuda" if torch.cuda.is_available() else "cpu")
        self._tokenizer = AutoTokenizer.from_pretrained(base, use_fast=True)
        # The default checkpoint's config only has LABEL_0/1/2; its model card
        # maps them to negative, neutral, positive, the same order as LABELS.
        # The "-latest" checkpoint names them, in that same order.
        self._model = AutoModelForSequenceClassification.from_pretrained(base)
        self._model.to(self.device)
        self._model.eval()


def baseline_predictor(base_model: str | None = None) -> BaselinePredictor:
    return BaselinePredictor(base_model)


def predictor_for(model: str, base_model: str | None = None):
    """The predictor to score ``model`` with: a baseline, or a served model."""
    if is_baseline(model):
        return baseline_predictor(base_model)
    return load_predictor(model)


def evaluate_predictions(
    model: str,
    texts,
    labels,
    batch_size=DEFAULT_BATCH_SIZE,
    base_model: str | None = None,
):
    """Score one model against labelled texts.

    ``texts`` must be raw: the predictor applies the same preprocessing the
    model was trained with, so preprocessing here as well would apply it twice.
    """
    predictor = predictor_for(model, base_model)
    labels = np.asarray(labels)

    probabilities = []
    for start in range(0, len(texts), batch_size):
        batch = list(texts[start : start + batch_size])
        probabilities.append(predictor.predict_proba(batch))
    stacked = np.vstack(probabilities) if probabilities else np.zeros((0, len(LABELS)))

    return compute_metrics(labels, np.argmax(stacked, axis=1))


def evaluate_model(
    model: str,
    split: str = DEFAULT_SPLIT,
    batch_size: int = DEFAULT_BATCH_SIZE,
    dataset=None,
    base_model: str | None = None,
) -> dict:
    """Evaluate one model on a dataset split and write its metrics record."""
    dataset = load_raw_dataset() if dataset is None else dataset
    texts = dataset[split]["text"]
    labels = dataset[split]["label"]

    LOGGER.info("Evaluating %s on %s (%d examples)...", model, split, len(labels))
    metrics = evaluate_predictions(
        model, texts, labels, batch_size=batch_size, base_model=base_model
    )
    LOGGER.info("  accuracy=%.4f macro F1=%.4f", metrics["accuracy"], metrics["f1_macro"])

    report = update_record(model, split, metrics, labels, batch_size, base_model)
    save_json(report, METRICS_DIR / f"{model}.json")
    return report


def update_record(
    model: str,
    split: str,
    metrics: dict,
    labels,
    batch_size: int,
    base_model: str | None = None,
) -> dict:
    """Merge an evaluation into the model's existing metrics record.

    Training writes that record, and it carries the hyperparameters, the split
    sizes and the class distribution the model was fitted on. An evaluation adds
    a measurement to it; it must not overwrite it, or the provenance behind a
    published number disappears the first time anyone runs the evaluation.

    The baseline has no training record here, so its first evaluation creates
    one that says what it is: the base checkpoint, not fine-tuned.
    """
    evaluation = {
        "split": split,
        "size": len(labels),
        "batch_size": batch_size,
        "class_distribution": class_distribution(labels),
        "evaluated_at": datetime.now(UTC).isoformat(timespec="seconds"),
    }

    path = METRICS_DIR / f"{model}.json"
    if path.exists():
        record = load_json(path)
        record.setdefault("metrics", {})[split] = metrics
        record["evaluation"] = evaluation
        return record

    # No training record: this model was trained elsewhere, or the reports
    # directory was cleaned. Say so rather than implying hyperparameters we
    # cannot know.
    baseline = is_baseline(model)
    record = build_report(
        model=model,
        hyperparameters=baseline_hyperparameters(base_model) if baseline else {},
        dataset={"name": DATASET_NAME, "config": DATASET_CONFIG},
        metrics={split: metrics},
        display_name=baseline_display_name(base_model) if baseline else None,
    )
    record["evaluation"] = evaluation
    return record


def evaluate_models(
    models: list[str] | None = None,
    split: str = DEFAULT_SPLIT,
    batch_size: int = DEFAULT_BATCH_SIZE,
    include_base: bool = False,
    base_model: str | None = None,
) -> list[dict]:
    """Evaluate several models, skipping any whose artifacts are unavailable.

    ``include_base`` adds an untouched base checkpoint, fetched from the Hub:
    the configured one, or ``base_model``.
    """
    requested = [resolve_model(m) for m in models] if models else available_models()

    # Filter before touching the dataset, as src.calibration does: on a fresh
    # clone `--models lstm` is a normal thing to ask for, and downloading
    # tweet_eval only to report that there is nothing to evaluate is wasted work.
    usable = []
    for model in requested:
        reason = check_artifacts(model)
        if reason is not None:
            LOGGER.warning("Skipping %s: %s", model, reason)
            continue
        usable.append(model)
    if include_base:
        # Nothing local to check: the checkpoint comes from the Hub on load.
        usable.append(baseline_key(base_model))

    if not usable:
        LOGGER.warning("No usable models. Run `make fetch-weights` first.")
        return []

    dataset = load_raw_dataset()

    reports = []
    for model in usable:
        try:
            reports.append(
                evaluate_model(
                    model,
                    split,
                    batch_size=batch_size,
                    dataset=dataset,
                    base_model=base_model if is_baseline(model) else None,
                )
            )
        # OSError is what transformers raises when the Hub is unreachable.
        except (ModelUnavailableError, OSError) as error:
            LOGGER.warning("Skipping %s: %s", model, error)
    return reports


def load_reports(models: list[str] | None = None) -> list[dict]:
    """Read previously written metrics records from reports/metrics/.

    Baseline records are included by default when they exist, the configured
    base's and any alternative's, so the table shows them beside the
    fine-tuned model without being asked.
    """
    if not models:
        baselines = sorted(
            path.stem for path in METRICS_DIR.glob(f"{BASELINE_KEY}*.json")
        )
        models = [*MODEL_KEYS, *baselines]
    reports = []
    for model in models:
        path = METRICS_DIR / f"{model}.json"
        if path.exists():
            reports.append(load_json(path))
    return reports


def example_count(report: dict, split: str):
    """How many examples a split's scores were measured on.

    Records written by training carry every split's size; records written by an
    evaluation carry only the split that was evaluated.
    """
    evaluation = report.get("evaluation") or {}
    if evaluation.get("split") == split and "size" in evaluation:
        return evaluation["size"]

    dataset = report.get("dataset") or {}
    sizes = dataset.get("split_sizes") or {}
    return sizes.get(split, dataset.get("size", "-"))


def _ranking_score(report: dict) -> tuple:
    """Sort key placing the best model first.

    Ranked on the evaluated split where there is one, so the table opens with
    the model that actually scored highest rather than with whichever model's
    key sorts first alphabetically.
    """
    metrics = report.get("metrics") or {}
    evaluated = (report.get("evaluation") or {}).get("split")
    if evaluated and evaluated in metrics:
        best = metrics[evaluated].get("f1_macro", 0.0)
    else:
        best = max((m.get("f1_macro", 0.0) for m in metrics.values()), default=0.0)
    return (-best, report.get("model", ""))


_ROW = "| {name} | {split} | {size} | {acc:.4f} | {f1:.4f} | {recall} | {per} |"


def markdown_table(reports: list[dict]) -> str:
    """Render reports as a Markdown table, ready to paste into the README."""
    if not reports:
        return "_No metrics recorded yet. Run `python -m src.evaluate`._"

    header = (
        "| Model | Split | Examples | Accuracy | Macro F1 | Macro recall | "
        + " | ".join(f"F1 {label}" for label in LABELS)
        + " |"
    )
    divider = "|" + "---|" * (6 + len(LABELS))
    rows = [header, divider]

    for report in sorted(reports, key=_ranking_score):
        for split, metrics in report["metrics"].items():
            per_class = metrics.get("f1_per_class", [])
            rows.append(
                _ROW.format(
                    name=report.get("display_name", report["model"]),
                    split=split,
                    size=example_count(report, split),
                    acc=metrics["accuracy"],
                    f1=metrics["f1_macro"],
                    recall=_optional_score(metrics.get("recall_macro")),
                    per=" | ".join(f"{value:.4f}" for value in per_class),
                )
            )
    return "\n".join(rows)


def _optional_score(value) -> str:
    """A score, or ``n/a`` for records written before the metric existed.

    Macro recall was added after the committed records were produced, so the
    table must render them until ``make evaluate`` is rerun, not crash.
    """
    return "n/a" if value is None else f"{value:.4f}"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--models",
        nargs="+",
        choices=[*MODEL_KEYS, *MODEL_ALIASES],
        metavar="MODEL",
        help="models to evaluate (default: every available model)",
    )
    parser.add_argument("--split", default=DEFAULT_SPLIT)
    parser.add_argument("--batch-size", type=int, default=DEFAULT_BATCH_SIZE)
    parser.add_argument(
        "--include-base",
        action="store_true",
        help=(
            f"also score {ROBERTA_CONFIG.base_model} as published, without our "
            "fine-tuning (downloads it from the Hub)"
        ),
    )
    parser.add_argument(
        "--base-model",
        default=None,
        metavar="CHECKPOINT",
        help=(
            "with --include-base, score this checkpoint instead of the configured "
            "base; its record is written beside the default's, not over it"
        ),
    )
    parser.add_argument(
        "--table-only",
        action="store_true",
        help="print the table from existing reports without evaluating",
    )
    args = parser.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(message)s")

    if args.table_only:
        reports = load_reports(args.models)
    else:
        reports = evaluate_models(
            args.models,
            args.split,
            args.batch_size,
            include_base=args.include_base,
            base_model=args.base_model,
        )

    print()
    print(markdown_table(reports))
    return 0 if reports else 1


if __name__ == "__main__":
    sys.exit(main())
