"""Evaluate trained models and record the results as build artifacts.

Run it as a module::

    python -m src.evaluate                      # every available model, test split
    python -m src.evaluate --models lr lstm
    python -m src.evaluate --split validation
    python -m src.evaluate --table-only         # re-print the table, evaluate nothing

Each run writes reports/metrics/<model>.json and prints a Markdown table meant to
be pasted straight into the README. That indirection is the point: the project's
documentation once claimed 92-95% accuracy for a model whose own checkpoint
recorded 78.9%, because the numbers were typed by hand and the training scripts
printed their metrics and discarded them. A number that cannot be regenerated by
a command is not evidence.
"""

from __future__ import annotations

import argparse
import logging
import sys

import numpy as np

from src.config import (
    DATASET_CONFIG,
    DATASET_NAME,
    LABELS,
    METRICS_DIR,
    MODEL_KEYS,
)
from src.data import class_distribution, load_raw_dataset
from src.inference.predictor import (
    ModelUnavailableError,
    available_models,
    check_artifacts,
    load_predictor,
)
from src.utils.io import load_json, save_json
from src.utils.metrics import build_report, compute_metrics

LOGGER = logging.getLogger(__name__)

DEFAULT_SPLIT = "test"
DEFAULT_BATCH_SIZE = 64


def evaluate_predictions(model: str, texts, labels, batch_size=DEFAULT_BATCH_SIZE):
    """Score one model against labelled texts.

    ``texts`` must be raw: the predictor applies the same preprocessing the
    model was trained with, so preprocessing here as well would apply it twice.
    """
    predictor = load_predictor(model)
    labels = np.asarray(labels)

    probabilities = []
    for start in range(0, len(texts), batch_size):
        batch = list(texts[start : start + batch_size])
        probabilities.append(predictor.predict_proba(batch))
    stacked = np.vstack(probabilities) if probabilities else np.zeros((0, len(LABELS)))

    return compute_metrics(labels, np.argmax(stacked, axis=1))


def evaluate_model(
    model: str,
    split: str = DEFAULT_SPLIT,
    batch_size: int = DEFAULT_BATCH_SIZE,
    dataset=None,
) -> dict:
    """Evaluate one model on a dataset split and write its metrics record."""
    dataset = load_raw_dataset() if dataset is None else dataset
    texts = dataset[split]["text"]
    labels = dataset[split]["label"]

    LOGGER.info("Evaluating %s on %s (%d examples)...", model, split, len(labels))
    metrics = evaluate_predictions(model, texts, labels, batch_size=batch_size)
    LOGGER.info(
        "  accuracy=%.4f macro F1=%.4f", metrics["accuracy"], metrics["f1_macro"]
    )

    report = build_report(
        model=model,
        hyperparameters={"evaluation_batch_size": batch_size},
        dataset={
            "name": DATASET_NAME,
            "config": DATASET_CONFIG,
            "split": split,
            "size": len(labels),
            "class_distribution": class_distribution(labels),
        },
        metrics={split: metrics},
    )
    save_json(report, METRICS_DIR / f"{model}.json")
    return report


def evaluate_models(
    models: list[str] | None = None,
    split: str = DEFAULT_SPLIT,
    batch_size: int = DEFAULT_BATCH_SIZE,
) -> list[dict]:
    """Evaluate several models, skipping any whose artifacts are unavailable."""
    requested = models or available_models()
    dataset = load_raw_dataset()

    reports = []
    for model in requested:
        reason = check_artifacts(model)
        if reason is not None:
            LOGGER.warning("Skipping %s: %s", model, reason)
            continue
        try:
            reports.append(
                evaluate_model(model, split, batch_size=batch_size, dataset=dataset)
            )
        except ModelUnavailableError as error:
            LOGGER.warning("Skipping %s: %s", model, error)
    return reports


def load_reports(models: list[str] | None = None) -> list[dict]:
    """Read previously written metrics records from reports/metrics/."""
    reports = []
    for model in models or MODEL_KEYS:
        path = METRICS_DIR / f"{model}.json"
        if path.exists():
            reports.append(load_json(path))
    return reports


def markdown_table(reports: list[dict]) -> str:
    """Render reports as a Markdown table, ready to paste into the README."""
    if not reports:
        return "_No metrics recorded yet. Run `python -m src.evaluate`._"

    header = (
        "| Model | Split | Examples | Accuracy | Macro F1 | "
        + " | ".join(f"F1 {label}" for label in LABELS)
        + " |"
    )
    divider = "|" + "---|" * (5 + len(LABELS))
    rows = [header, divider]

    for report in sorted(reports, key=lambda item: item["model"]):
        for split, metrics in report["metrics"].items():
            per_class = metrics.get("f1_per_class", [])
            rows.append(
                "| {name} | {split} | {size} | {acc:.4f} | {f1:.4f} | {per} |".format(
                    name=report.get("display_name", report["model"]),
                    split=split,
                    size=report.get("dataset", {}).get("size", "-"),
                    acc=metrics["accuracy"],
                    f1=metrics["f1_macro"],
                    per=" | ".join(f"{value:.4f}" for value in per_class),
                )
            )
    return "\n".join(rows)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--models", nargs="+", choices=MODEL_KEYS,
        help="models to evaluate (default: every available model)",
    )
    parser.add_argument("--split", default=DEFAULT_SPLIT)
    parser.add_argument("--batch-size", type=int, default=DEFAULT_BATCH_SIZE)
    parser.add_argument(
        "--table-only", action="store_true",
        help="print the table from existing reports without evaluating",
    )
    args = parser.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(message)s")

    if args.table_only:
        reports = load_reports(args.models)
    else:
        reports = evaluate_models(args.models, args.split, args.batch_size)

    print()
    print(markdown_table(reports))
    return 0 if reports else 1


if __name__ == "__main__":
    sys.exit(main())
