"""Evaluate trained models and record the results as build artifacts.

Run it as a module::

    python -m src.evaluate                      # every available model, test split
    python -m src.evaluate --models lr lstm
    python -m src.evaluate --split validation
    python -m src.evaluate --table-only         # re-print the table, evaluate nothing

Each run writes reports/metrics/<model>.json and prints a Markdown table meant to
be pasted straight into the README. That indirection is the point: the project's
documentation once claimed 92-95% accuracy for a model whose own checkpoint
recorded 78.9%, because the numbers were typed by hand and the training scripts
printed their metrics and discarded them. A number that cannot be regenerated by
a command is not evidence.
"""

from __future__ import annotations

import argparse
import logging
import sys
from datetime import UTC, datetime

import numpy as np

from src.config import (
    DATASET_CONFIG,
    DATASET_NAME,
    LABELS,
    METRICS_DIR,
    MODEL_ALIASES,
    MODEL_KEYS,
    resolve_model,
)
from src.data import class_distribution, load_raw_dataset
from src.inference.predictor import (
    ModelUnavailableError,
    available_models,
    check_artifacts,
    load_predictor,
)
from src.utils.io import load_json, save_json
from src.utils.metrics import build_report, compute_metrics

LOGGER = logging.getLogger(__name__)

DEFAULT_SPLIT = "test"
DEFAULT_BATCH_SIZE = 64


def evaluate_predictions(model: str, texts, labels, batch_size=DEFAULT_BATCH_SIZE):
    """Score one model against labelled texts.

    ``texts`` must be raw: the predictor applies the same preprocessing the
    model was trained with, so preprocessing here as well would apply it twice.
    """
    predictor = load_predictor(model)
    labels = np.asarray(labels)

    probabilities = []
    for start in range(0, len(texts), batch_size):
        batch = list(texts[start : start + batch_size])
        probabilities.append(predictor.predict_proba(batch))
    stacked = np.vstack(probabilities) if probabilities else np.zeros((0, len(LABELS)))

    return compute_metrics(labels, np.argmax(stacked, axis=1))


def evaluate_model(
    model: str,
    split: str = DEFAULT_SPLIT,
    batch_size: int = DEFAULT_BATCH_SIZE,
    dataset=None,
) -> dict:
    """Evaluate one model on a dataset split and write its metrics record."""
    dataset = load_raw_dataset() if dataset is None else dataset
    texts = dataset[split]["text"]
    labels = dataset[split]["label"]

    LOGGER.info("Evaluating %s on %s (%d examples)...", model, split, len(labels))
    metrics = evaluate_predictions(model, texts, labels, batch_size=batch_size)
    LOGGER.info("  accuracy=%.4f macro F1=%.4f", metrics["accuracy"], metrics["f1_macro"])

    report = update_record(model, split, metrics, labels, batch_size)
    save_json(report, METRICS_DIR / f"{model}.json")
    return report


def update_record(model: str, split: str, metrics: dict, labels, batch_size: int) -> dict:
    """Merge an evaluation into the model's existing metrics record.

    Training writes that record, and it carries the hyperparameters, the split
    sizes and the class distribution the model was fitted on. An evaluation adds
    a measurement to it; it must not overwrite it, or the provenance behind a
    published number disappears the first time anyone runs the evaluation.
    """
    evaluation = {
        "split": split,
        "size": len(labels),
        "batch_size": batch_size,
        "class_distribution": class_distribution(labels),
        "evaluated_at": datetime.now(UTC).isoformat(timespec="seconds"),
    }

    path = METRICS_DIR / f"{model}.json"
    if path.exists():
        record = load_json(path)
        record.setdefault("metrics", {})[split] = metrics
        record["evaluation"] = evaluation
        return record

    # No training record: this model was trained elsewhere, or the reports
    # directory was cleaned. Say so rather than implying hyperparameters we
    # cannot know.
    record = build_report(
        model=model,
        hyperparameters={},
        dataset={"name": DATASET_NAME, "config": DATASET_CONFIG},
        metrics={split: metrics},
    )
    record["evaluation"] = evaluation
    return record


def evaluate_models(
    models: list[str] | None = None,
    split: str = DEFAULT_SPLIT,
    batch_size: int = DEFAULT_BATCH_SIZE,
) -> list[dict]:
    """Evaluate several models, skipping any whose artifacts are unavailable."""
    requested = [resolve_model(m) for m in models] if models else available_models()

    # Filter before touching the dataset, as src.calibration does: on a fresh
    # clone `--models lstm` is a normal thing to ask for, and downloading
    # tweet_eval only to report that there is nothing to evaluate is wasted work.
    usable = []
    for model in requested:
        reason = check_artifacts(model)
        if reason is not None:
            LOGGER.warning("Skipping %s: %s", model, reason)
            continue
        usable.append(model)

    if not usable:
        LOGGER.warning("No usable models. Run `make fetch-weights` first.")
        return []

    dataset = load_raw_dataset()

    reports = []
    for model in usable:
        try:
            reports.append(
                evaluate_model(model, split, batch_size=batch_size, dataset=dataset)
            )
        except ModelUnavailableError as error:
            LOGGER.warning("Skipping %s: %s", model, error)
    return reports


def load_reports(models: list[str] | None = None) -> list[dict]:
    """Read previously written metrics records from reports/metrics/."""
    reports = []
    for model in models or MODEL_KEYS:
        path = METRICS_DIR / f"{model}.json"
        if path.exists():
            reports.append(load_json(path))
    return reports


def example_count(report: dict, split: str):
    """How many examples a split's scores were measured on.

    Records written by training carry every split's size; records written by an
    evaluation carry only the split that was evaluated.
    """
    evaluation = report.get("evaluation") or {}
    if evaluation.get("split") == split and "size" in evaluation:
        return evaluation["size"]

    dataset = report.get("dataset") or {}
    sizes = dataset.get("split_sizes") or {}
    return sizes.get(split, dataset.get("size", "-"))


def _ranking_score(report: dict) -> tuple:
    """Sort key placing the best model first.

    Ranked on the evaluated split where there is one, so the table opens with
    the model that actually scored highest rather than with whichever model's
    key sorts first alphabetically.
    """
    metrics = report.get("metrics") or {}
    evaluated = (report.get("evaluation") or {}).get("split")
    if evaluated and evaluated in metrics:
        best = metrics[evaluated].get("f1_macro", 0.0)
    else:
        best = max((m.get("f1_macro", 0.0) for m in metrics.values()), default=0.0)
    return (-best, report.get("model", ""))


_ROW = "| {name} | {split} | {size} | {acc:.4f} | {f1:.4f} | {recall} | {per} |"


def markdown_table(reports: list[dict]) -> str:
    """Render reports as a Markdown table, ready to paste into the README."""
    if not reports:
        return "_No metrics recorded yet. Run `python -m src.evaluate`._"

    header = (
        "| Model | Split | Examples | Accuracy | Macro F1 | Macro recall | "
        + " | ".join(f"F1 {label}" for label in LABELS)
        + " |"
    )
    divider = "|" + "---|" * (6 + len(LABELS))
    rows = [header, divider]

    for report in sorted(reports, key=_ranking_score):
        for split, metrics in report["metrics"].items():
            per_class = metrics.get("f1_per_class", [])
            rows.append(
                _ROW.format(
                    name=report.get("display_name", report["model"]),
                    split=split,
                    size=example_count(report, split),
                    acc=metrics["accuracy"],
                    f1=metrics["f1_macro"],
                    recall=_optional_score(metrics.get("recall_macro")),
                    per=" | ".join(f"{value:.4f}" for value in per_class),
                )
            )
    return "\n".join(rows)


def _optional_score(value) -> str:
    """A score, or ``n/a`` for records written before the metric existed.

    Macro recall was added after the committed records were produced, so the
    table must render them until ``make evaluate`` is rerun, not crash.
    """
    return "n/a" if value is None else f"{value:.4f}"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--models",
        nargs="+",
        choices=[*MODEL_KEYS, *MODEL_ALIASES],
        metavar="MODEL",
        help="models to evaluate (default: every available model)",
    )
    parser.add_argument("--split", default=DEFAULT_SPLIT)
    parser.add_argument("--batch-size", type=int, default=DEFAULT_BATCH_SIZE)
    parser.add_argument(
        "--table-only",
        action="store_true",
        help="print the table from existing reports without evaluating",
    )
    args = parser.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(message)s")

    if args.table_only:
        reports = load_reports(args.models)
    else:
        reports = evaluate_models(args.models, args.split, args.batch_size)

    print()
    print(markdown_table(reports))
    return 0 if reports else 1


if __name__ == "__main__":
    sys.exit(main())
